---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-minio-secret-key
  namespace: minio-test
spec:
  encryptedData:
    secretKey: AgBBjCN3KQ6UPPetZAGlwPWA2MxMjBjfyv2pan6T0T3f3Si5pdlP+hJM5DR5MhNHbGViWkyAl8eR9foKnYGFsg3IW3/fMaaTlYv3o5va9NxGmy5H78e29Rd5ISo3oDtq34MfvEY3/wjSTXSfWnWuMNvuOWx2qSCH+8qcqWQy/xhzBiQ0YOeMHvgVW2q5r1mPlUNoAIY2RHNKsRWrO/Q6vbF+mRF/KjPQLf/3RyenQ0F8Eynrc+OrtgiBhc0e789vWrLaF3upHV2hpoKBTNzT0xaYZaMin1iQjBPi8ZKNt440m7yHeGlgHkB9GpTCJjuYSaZAr2qpf4MmysCB2TkeFlbxkQX+BgMil4Xfbe53MqqIUpY/94XqIQiIf9lzE0VgehsU7bLnJ1TStgb3iFdzur0SSjqhsqL6nu02FqSwR2SCPqPom105PuYiAAblstrhNTMHc2rsLGmQsSyAnEtUVPrQMcn2Lmggvjs/fbcGpdoWgxLNZ9eMCDnrdkIcNJEXtPftZuCtI1BcbGgEmeTcO50tWMpgWFSFIiij8NcPFDU8iyo2d1J5KK51Z94i5zEfUxSG3hier4ngr0LaIyzFPYO09E/xHZqvXJ2AcJpt1sbwuMI0oJWlAxhIR9Q34vc26MPIFb5zYnYUhc1Ly9oXUIUxBiLSNxpFEtJ/JVXbldRS7EJMoMn4zz7Hp4xp7DdGFCzPXiMrPuxzGPhGropTxAgonao6LwhVaG37MlplRZz7p7EN4vFrGo5v4oW6MC8BgBPi
  template:
    metadata:
      creationTimestamp: null
      name: loki-minio-secret-key
      namespace: minio-test
    type: Opaque
