---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root-user-secret
  namespace: minio-test
spec:
  encryptedData:
    rootPassword: AgAa+UZvNqoVzPBebbjA4O4ArDrtNw90Qha9K8V893sW2ktQE69GCCb0szsWOqszz8U44X/Y2xerqcADnFGog3Vi/7gmq0ZBZJa9abAFpjVLAyevAip13iPxA99OxPKr87+UYjJZaO3PVxqW496yUofA+/eY8EujWdWfdQHqUEI+US9fez/WA6SYP/WKDj34yDGYVqeYRpEgaP27qjyGum1wiVsUkBAlS/x3rbJcW0+ZqbEyI8mHQdslklKi03FgygrVMNwkQgjKQYx3OXfeowhaTKgw0NXC571cj/fANPI1c3pgXZV8QjKaJV1UjjgU3xBUn+0He38ef3bm9vLUCFxuchfXN0sUbd05P99FiuNeT0ApvMuJKOHK6CfR08sFRA6R+4M2uUg8YWttfSsxUfauiCM5bzuJ0RfuFhQzPl4Llbl1O7hbTPC5lLNts05Kjt5duft7us9glH0lGQ3ZRe8VzLvc04zO9cI4SrouMieS1PtOr9WfQO+KJW5zKM6tD3STLTwx1PIXrKwJX9cvpRCAeDXWeX2hQSP2Xwy/A2zTqjz4cwKgPopEmzFyBvcCBSQReNBGoblJ4HBFtn3fAXsL7+B/Cb9JdCKPMqJWpx/5YDbkDCGEHeAC4CZmS4AOmHenW40VB4m2Qx5OnQwBPhoetIBmepKljjTvucLbzWRdjKzE1Kgk8bGNuiV/S/+8vrUsW7HzUXgOIKQOiEzn6w9c4NGA1fEHDbv40A==
    rootUser: AgCIRikDkqB+3dRx0ft3pM3xUD+8AIxAkoE290rZnbLg4g1iK6GWdnIROk+S3ayK198tdSjg97KUBsdUhs6ZmLAlaF8cHnRCFSn40btDtUW7ke5pICxSui0WkaMUIzdO/lsDS0+KgOG2MFPsWC1Gor07ZJ2sZeZAX6jDwJBr6C4iQV8YwjBzzZqv4o28TML9GW0eNhMXLRbFBxX0+aXyL9dhLKsZj9Xr5ZqvvIlY4kJP81nK3dLkHFwrUKmPfCFmScIPNgSkGkXRkYw1sbwbTBOMdrUfFonmtUcQlweIDc88RF94r25ksggm+U23fi4MKKAqxoh+iIpqw4NPwDHj8PItN+E+oAKVSub76DJz1Ql5GhfBMaepNP4R7hfGW4Q6Kk611gRXHztU/QDhPiIlBy3UllGHihV1UszqXWQmmqSQ+GGp8R8YjtXlTCmXSUkuttilBNK7UoebdxRwZ7S9a/hXzIg0ME6r3x8INDDWM4RTP/WKRkrad/iUtoBCu+g61kd9WVLVrXm30tIio+0le7oVw+HPBkwL8uUNmaXsDPI2wAagFbf/zOe03tTBCsdHHPlOtHDuUvY6Pw5fO1Ei/gnrni6Ap1sp7UET1Lc1mlVBgxyiAQOw0NoZbGcmnHwtBctZ16n2xhV0OVxMMCfo+mIvchadlzkQIiq95fK7MDLfnSn7zt9VJwDDgJQXSIa3HSaAXCp3ivJfEyIxw5l7HzvrwuQNLTQ/vd/dVQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-root-user-secret
      namespace: minio-test
    type: Opaque
