---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-minio-secret-key
  namespace: minio_test
spec:
  encryptedData:
    secretKey: AgBjF5eFenVbK4/olOZVsHE+wkLT5hFgVhtHz0c7alFRZDNOL0COXZANTcM25pQVc80C4wYB3n4KORV9xWsIgxsOYKj5Umj13X8yDrnvRZ0fCdfeHR+StXEXrBQWUNdPYt/3eUMViaX3B/RYeI+MHO7gToghVmhek9enuuyiyCeo/PVf4YB+t8NQrlD26v0IEg/aCHpTXz0KCgpYDp4IyLhwa6zD9z6NiGccGQXpZb9P9dtykMKrp90XP8TApZduIcNGKdrOlzbLuaot62YscO0sdoo6E7biHQUio28LJ6/mYa1hZ7b0W3FCi5yI+isFU4TLFf9GspIBqD/rlbCGuZkKb0Gd4nRyN8hsAcpmLEtnnhOSSSTq/saMsBaH0y0czFoIR9ah/Hmr3YQ74/0QjA9s4RZMUbsmGlVuq9MBe/Xr9zCUQzZzK0OUfMwOWjqXcwABgMs7VkhQcvMrL5yWsANvY7VayPusazmS4r9bJU66wZ1TAYwfRiaPq82ukuLz1Ua9/V7sip0Kk+TlRcTmv02V8aJlIQPhagx1j4ZS1DOTdMRGbulsfca3jCZ2OUOv/df27knXRdWN1wXYZcMnAMDPLHRgTlzWdL30CTKxS6xCNYdibummQIvkr4sCdzmTz6mSMTCT7QAzMrdDyfEwj2ChI5i8FrILFyqpSoB7skFgI6YVFDO3XihJ6V+LKu72BxrM6SpLGuhwV2ZGfnkqCpUHF0NyKjqV9QhVATyIcAzp01UjevPT64kqWyvfzDCMqIa1
  template:
    metadata:
      creationTimestamp: null
      name: loki-minio-secret-key
      namespace: minio_test
    type: Opaque
