---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret-key
  namespace: minio-test
spec:
  encryptedData:
    secretKey: AgBLDFE8bkpOlZ+7LxXReCzNcvvzAlYz92iXVdj0T86+3yErtRJUX4e2pxOBc1Bw4U1zLiwNFCa9xX8Go5a5KU9AJxuHYeuvEZ4B8fluDAFwiJTB2lixVJRYQT29ktyPYoP2ANJxSCVYQyotOXFaKbwRjgtPiisxUZ9OqMIKGXg60vfKT8+86kNXW//njbZwI0qzNAY+b7uu7TclS733d5fDLm657ErMno+nBswaff5+3Z49OSX5c10UD5Oij45So54jsGRvaCMHQGkLnCt92gsQVJ1Y7RUXpOBD/J4KrRIEzF4Lu0KIhEwppZ8HSyMkftbn5GtKldcaAjXzbVb2NMgfENn/EvgReiqWteGAF1cvqVqn3caz7/rhvfv5mDalOR6lxW/65RSZZtnvabAzNAi/nLtIO7+SPQsn3uCEJFt8NWo+8R7P0czCFCCjVHzLZ5oWmf9vFxIs6OQJQGoAdibQdQzK66m81jrHGUW2YSCRmEk6guLplB/cs2umt2cvDRL7Ix4D+Ad2pq+ShvapYtXW3QGLLQeqjFQpZdy7a2PjN3abGltSc0uzC896DQTTVsDbKI3vCW7/3kThl02/7zOBRvHEswjKLvm3VuHUQu70ljE2Ge+R3N7MuFuTR+/azvk5be4MjuSPIQuDXvBWSxTu4MwioLJmWmhyC7F3KG2Vi6yEMq6HipN4Vug7xXzjj19RM8d+ojdlCAbrAGsj+98/CUH0h93JEXIlcA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret-key
      namespace: minio-test
    type: Opaque
