# Default values for lagoon-remote.
# global values which can affect subcharts
global:
  # set to true to enable openshift support
  openshift: false
  rabbitMQUsername: ""
  rabbitMQPassword: ""
  rabbitMQHostname: ""
imagePullSecrets: []
logsDispatcherHost: lagoon-logging-logs-dispatcher.lagoon-logging.svc.cluster.local
# If this value is set, it will create an `mxout` ExternalName service in the
# deployed namespace pointing at the given host. This service can then be used
# by workloads running in-cluster to connect to a platform-provided mailserver.
mxoutHost: ""
# this default image tag is set for all services and can be overridden
# on the service level, if not set it uses chart appVersion
imageTag: ""
dockerHost:
  image:
    repository: uselagoon/docker-host
    pullPolicy: Always
    # Overrides the image tag whose default is "latest".
    tag: v3.5.0
  name: docker-host
  registry: registry.lagoon.svc:5000
  repositoryToUpdate: amazeeio|lagoon
  pruneImagesUntil: 1h
  replicaCount: 1
  ## proxy configuration
  # httpProxy: ""
  # httpsProxy: ""
  # noProxy: ""
  # add extra environment variables if required
  extraEnvs: null
  storage:
    create: true
    size: 370Gi
    # className sets the storageClassName for the docker-host PVC. This is
    # useful if the docker-host requires a specific storage class for features
    # such as increased IOPS.
    #
    # WARNING: On platforms such as AKS not all storage volume classes can be
    # bound to all node types. So if you configure a storage class that can't
    # be bound to any nodes in the cluster it will cause the docker-host pod to
    # fail to schedule. For example AKS requires Premium Storage suport on the
    # node for the managed-premium storage class.
    #
    # If className is not defined the chart will not set any specify storage
    # class on the PVC, effectively falling back to the cluster default.
    #
    # className: computerome-nfs
  networkPolicy:
    # Specifies whether the docker-host network policy should be enabled
    enabled: true
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname
    # template
    name: null
  podSecurityContext: {}
  securityContext:
    privileged: true
    seLinuxOptions:
      # Ensures selinux relabeling is disabled, this would case the container never to start
      # as there can be so many files in the persistent storage
      type: spc_t
  resources: {}
  service:
    type: ClusterIP
    port: 2375
  nodeSelector:
    node-role.kubernetes.io/build: ""
  tolerations:
    - key: noderole.dplplatform
      operator: Equal
      value: build
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/build
                operator: In
                values:
                  - ""
# sshCore creates a restricted, non-expiring ServiceAccount token for use by
# lagoon-core.
sshCore:
  enabled: true
  serviceAccount:
    annotations: {}
    # The name of the service account to use.
    # If not set, a name is generated using the fullname
    # template
    name: ""
# sshPortal is an optional service providing low-latency SSH connectivity to
# Lagoon environments.
sshPortal:
  enabled: false
  replicaCount: 2
  image:
    repository: ghcr.io/uselagoon/lagoon-ssh-portal/ssh-portal
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v0.37.0
  service:
    type: LoadBalancer
    ports:
      sshserver: 22
    annotations: {}
  metricsService:
    type: ClusterIP
    ports:
      metrics: 9912
  podAnnotations: {}
  securityContext: {}
  resources: {}
  additionalEnvs: {}
  serviceAccount:
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname
    # template
    name: ""
  serviceMonitor:
    enabled: true
  # host keys, PEM encoded
  hostKeys:
    ecdsa: ""
    ed25519: ""
    rsa: ""
    # Log access via SSH is disabled by default.
    # Uncomment this line to enable log access via SSH.
    # logAccessEnabled: true
# This subchart is disabled by default until this build-deploy type is in
# widespread use.
lagoon-build-deploy:
  enabled: true
  # these values are used by the lagoon-build-deploy controller and do not have
  # sensible defaults.
  # lagoonTargetName:
  #ENCRYPT
  taskSSHHost: ENC[AES256_GCM,data:x/CrtOz+MnmdxafXyA==,iv:x+XMsNqqoU2b7xomNYaVfL83hdLs7w+wiNP4iq0xwsI=,tag:XfTdeaUkHqVCRQWAI0a5Jg==,type:str]
  taskSSHPort: 22
  taskAPIHost: api.lagoon.dplplat02.dpl.reload.dk
  # lagoonTokenHost: ""
  # lagoonTokenPort: ""
  # lagoonAPIHost: ""
  # sshPortalHost: ""
  # sshPortalPort: ""
  #ENCRYPT
  rabbitMQUsername: ENC[AES256_GCM,data:kism8RbK,iv:EOcYvtRVVMhJ6MyPynaaKfyC52ObKXcYUrgo+1TwcG0=,tag:HhCYZ/sbkwUTLLo5cShayw==,type:str]
  #ENCRYPT
  rabbitMQPassword: ENC[AES256_GCM,data:ORebOSZ8Cgy5nDv95HmtGqzL5ZAbuAzv0xixoHXB,iv:+eBFqTl5Tumu7zcEy7Vk0X0GSiO3I4b3ebg9Vs7r12k=,tag:Jwe9BMScJaYXGEXF3pUDag==,type:str]
  rabbitMQHostname: lagoon-core-broker.lagoon-core.svc.cluster.local
  lagoonTargetName: lagoon
  lagoonFeatureFlagDefaultRootlessWorkload: enabled
  # See the parent chart for the full range of values that can be passed here to control builds
  # https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-build-deploy/values.yaml
  extraArgs:
    - --enable-harbor=true
    - --harbor-url=https://harbor.lagoon.dplplat02.dpl.reload.dk
    - --harbor-api=https://harbor.lagoon.dplplat02.dpl.reload.dk/api/
    #ENCRYPT
    - ENC[AES256_GCM,data:IT80YAP7SF8ErOgNgrXQ1JXzAY9tquU=,iv:S5+SFV/HnXlRzWnGTcTXLIwqF627CfTIbKbIkdu3nt0=,tag:1OloLnHRY1anzKtL+plDFQ==,type:str]
    #ENCRYPT
    - ENC[AES256_GCM,data:P57KwoWZlnyLSS37HNO+RntM6aKLtR8TkqvKioQEgXsIVgeRkxU=,iv:zolligTvL4ZXqd26ZOXVxPS5qC9lOveBX82zXPXRVDA=,tag:EUcVmswnQYogmgOU4rQFmw==,type:str]
    - --enable-qos
    - --qos-max-builds=8
  nodeSelector:
    node-role.kubernetes.io/prod: ""
  tolerations:
    - key: noderole.dplplatform
      operator: Equal
      value: prod
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/prod
                operator: In
                values:
                  - ""
# dbaas-operator provisions database-as-a-service accounts for projects.
# Example provider configuration can be found in the dbaas-operator values.yaml
# https://github.com/amazeeio/charts/blob/main/charts/dbaas-operator/values.yaml
# This subchart is disabled by default for legacy reasons. It will be enabled
# by default in future as this is a core Lagoon feature.
dbaas-operator:
  enabled: true
  enableMariaDBProviders: true
  enableMongoDBProviders: true
  enablePostreSQLProviders: true
  mariadbProviders:
    production:
      environment: production
      hostname: mariadb-10-6-22-production-1.mariadb-10-6-22-production-1.svc.cluster.local
      readReplicaHostnames:
        - mariadb-10-6-22-production-1.mariadb-10-6-22-production-1.svc.cluster.local
      #ENCRYPT
      password: ENC[AES256_GCM,data:bpNQE568Apu47bZlUXNmBI1V+Bg6JnUh,iv:Kf5mYCfZq8k29yPcrenVMHcAR6dpGxEOEipjIp7xfWE=,tag:uHzvig8X+v47Xv+WpySNjw==,type:str]
      port: 3306
      #ENCRYPT
      user: ENC[AES256_GCM,data:snU1dw==,iv:QCQ9NPf3JYT2EouOOCaOM5sw/ILmZMH1CqcmbgLZHFY=,tag:2Js6E4hoLJbv9dKy7geE7g==,type:str]
    development:
      environment: development
      hostname: mariadb-10-06-01-test.mariadb-10-06-01-test.svc.cluster.local
      readReplicaHostnames:
        - mariadb-10-06-01-test.mariadb-10-06-01-test.svc.cluster.local
      #ENCRYPT
      password: ENC[AES256_GCM,data:ANOdV3Q+eGemQ4ZULRIu71u8FBD9oIZdQ366jg==,iv:UiUduHtdVGR1Ghz5rdVnV+neiwQDY7PcMxeIQUbFZKk=,tag:DY6qu0KPUKYiGYGVSH9CLw==,type:str]
      port: 3306
      #ENCRYPT
      user: ENC[AES256_GCM,data:L8YzUQ==,iv:KeTsuO2yxuN+jDFNT7EIw7AfS+4lzC++7JTfCOJyc2g=,tag:rjSr/W55E9rpQhDIWCOnyQ==,type:str]
  nodeSelector:
    node-role.kubernetes.io/prod: ""
  tolerations:
    - key: noderole.dplplatform
      operator: Equal
      value: prod
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/prod
                operator: In
                values:
                  - ""
# if you are using the dbaas-operator in a different release, you can define the http endpoint to use here
# setting this will always override whatever `dbaas-operator` would set, useful if you want to target a different endpoint
dbaasHTTPEndpoint: ""
# lagoon-insights-remote:
#   enabled: false
# burnAfterReading: false
insightsRemote:
  enabled: false
  # sets insights configMaps to be removed after being processed
  burnAfterReading: true
  replicaCount: 1
  # This is the secret used to sign JWT's injected into environments
  # This shouldn't need to be changed in most circumstances - here for completion
  # insightsTokenSecret: ""
  image:
    repository: uselagoon/insights-remote
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: v0.0.11
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # service:
  #   type: ClusterIP
  #   port: 80
  # ingress:
  #   enabled: false
  #   className: ""
  #   annotations: {}
  #     # kubernetes.io/ingress.class: nginx
  #     # kubernetes.io/tls-acme: "true"
  #   hosts:
  #     - host: chart-example.local
  #       paths:
  #         - path: /
  #           pathType: ImplementationSpecific
  #   tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector:
    node-role.kubernetes.io/prod: ""
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    port: 80
# the nats chart is a subchart which is configured for use by lagoon-remote
# nats subchart is configured for use by lagoon-remote
nats:
  enabled: false
  # inject additional config
  additionalVolumes:
    - name: lagoon-remote-nats-tls
      secret:
        secretName: lagoon-remote-nats-tls
  additionalVolumeMounts:
    - name: lagoon-remote-nats-tls
      mountPath: /etc/lagoon-remote-nats-tls
  nats:
    config:
      - name: lagoon-remote
        secret:
          secretName: lagoon-remote-nats-conf
  cluster:
    enabled: true
    name: lagoon-remote
    # internal cluster IPs are not routable, so don't advertise them
    noAdvertise: true
  natsbox:
    enabled: false
  # to connect to nats, pods must have the right label
  networkPolicy:
    enabled: true
    allowExternal: false
    # allow outbound leaf connection
    extraEgress:
      - ports:
          - port: 7422
            protocol: TCP
# Configuration for the nats subchart
natsConfig:
  # coreURL format nats://<username>:<password>@<host>:7422
  coreURL: ""
  tls: {}
  # If the lagoon-remote-nats-tls secret should be created by the
  # lagoon-remote chart, certificate values can be specified directly in
  # secretData. Configuring TLS this way also allows specifying a custom
  # ca.crt.
  #
  # secretData:
  #   ca.crt: |
  #     ...
  #   client.crt: |
  #     ...
  #   client.key: |
  #     ...
  #
  # If the TLS secret is created outside the lagoon-remote chart, it should
  # be named lagoon-remote-nats-tls. This secret should contain fields
  # tls.crt and tls.key, and the certificate should be issued by a public
  # authority.
storageCalculator:
  enabled: false
  # cronjob: 5 */12 * * *
  # ignoreRegex: "solr|redis"
  serviceAccount:
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname
    # template
    name: null
  metricsService:
    type: ClusterIP
    ports:
      metrics: 9912
  serviceMonitor:
    enabled: true
  image:
    repository: uselagoon/remote-calculator
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v0.6.0
sops:
  azure_kv:
    - vault_url: https://kv-dplplat01-c3b2.vault.azure.net
      name: sops-key
      version: d82fe2456d6e4c4aaaaf808226bd5769
      created_at: "2026-05-04T12:01:56Z"
      enc: jSWbvme_8nWqDEu4MpO609vGaZ0rd-5lqMbQ2Zp-jCw9lLKcR81V6FF9TzAVNkymFO5tH_BsGSg8SAMtKkQ3FMw5I-Tc0-bvDDzaLGDN2gDQcQ6KI0iK4_QslPZ25RK9T2VdjQEN9lZVEKfEIpixZyZkpJw9Ojmbjwt20JLmmH5EpFj99G6l7EHlQZXCn0zvaDRk1UD-pDWfrEQkcf9_6one42ZVvIT6iSNFXMcko2KdwrWNVEsqoM0-rB_HVgDNMZ0xXaeThXSRTCIdoCx4CUiys3GQJDRAUQDCOQVa1QiT_yN8mMGbH8jdgGUHs1LdTCx4rnw_llG7PJglFKxBN_xcqLEF3WhtHI-Vvbss1OpMBuofHPaQC2mH52Nq5lVy8mRdTfHixWsT-s6ZaxggnXE6cu0JLb3C980RWg0hiywUoIXajhp4N0p_J3YSOTxsvk-jiFcPhTftTnNOJ1hm9AcH10dXH_bdN-LKvJtKxTenDgXM-VxjEmkzKVnMdzTic-V-nB3WaQoWzwTwQ6idGO9WQ-sDER0-_voZYe_fk8hHZSEKYj7wovbf-iHWhwE-GyH9zZgITkxefG3gdp4FMAS1nzijs9c8BvDsDUDZOoLw1L4iP_LVKAtVdzwRBeXou2kDdbtlN87wMGoPonQLHUa80YFLv_JJNLzUrqC4dp0
  age:
    - recipient: age1q8yqc5jvhkk7ufj95tw25u3es0846pkrwgcd4pn9ctermr7e6cesn6l0gd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK0NoNlJKbDdOaERzNVpO
        VS9CamRSSFF1cnYzU1VsbDBtazdZTk5zaFJRCm5Zd05ZR250d3k4b25Ucm4vU3N1
        Nm5IR0l5WGF0KzBOK1ZEYzJwUEhMdWcKLS0tIHdkQkNtVFp4bW5Zb0tWdWcvbGUv
        R0NQSXo2bWxZYm04MTFZMzczK25sYTgKYs2Yvv9Q0lc1BkIJS2Z+NYm88wSI8ABJ
        NE0bQP1wHmEXgQfDogtd0N2KjO3R4F6LKAOIzif45r+v04mn/GoUDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T12:01:58Z"
  mac: ENC[AES256_GCM,data:t555/iqzFUrG90Df4TWFcargDTE6xxTsUnedjRY/0NaRQqCdZXUoBm/l4huTuv3okWwU3k06lcYF15AJqVOXG/rF9KlLlX3vkmO3uCmM/cUDYDA3nCB6CA9S+ljzL3D7453z6ZUKmBIInRwjq9yinp/0ZWAcSp2eaBYCQL5QLwM=,iv:tS7KhUFeG7zaJ8nVFPOKjkihIC1Dz+LjTPahp20lllk=,tag:zXYa18IHTJtEJ6VOs7wDKg==,type:str]
  encrypted_comment_regex: ENCRYPT
  version: 3.11.0
