{
 "title": "CMS BNF synkronisering",
 "description": "Overordnede statistikker for BNF-sync.",
 "tags": [ "cms" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(dpl_cms_deployment_info,environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Abonnenter per stream",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (stream) (dpl_cms_bnf_subscription_info{environment=\"$env\"})\n  * on (stream) group_left(name)\n    topk(1, dpl_cms_bnf_stream_info{environment=\"$env\"}) by (stream)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Antal steam-abonnementer pr. site",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(project) (dpl_cms_bnf_subscription_info{environment=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue depth (node update)",
   "type": "timeseries",
   "description": "Length of the bnf_client_node_update queue, zero-values filtered out.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by(project) (\n    dpl_cms_bnf_sync_queue_depth{queue=\"bnf_client_node_update\", environment=\"$env\"}\n  )[$__interval:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue depth (new content)",
   "type": "timeseries",
   "description": "Length of the bnf_client_new_content queue, zero-values filtered out.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(project) (\n  dpl_cms_bnf_sync_queue_depth{queue=\"bnf_client_new_content\", environment=\"$env\"}\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}