{
 "title": "cms deployment info fra YAML",
 "tags": [ "cms" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Deployed sites by version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(version) (dpl_cms_deployment_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current version per site",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "group by(project, environment, version) (dpl_cms_deployment_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current version count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(version, environment) (dpl_cms_deployment_info)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}