apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  datasource:
    name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://kube-prometheus-stack-prometheus.monitoring:9090/
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
  instanceSelector:
    matchLabels:
      dashboards: grafana
