# This manifest will fire up a customer Kubernetes Job in moduletest namepaces.
# It will synchronize all files as well as the database from the corresponding main environment to the moduletest environment

apiVersion: batch/v1
kind: CronJob
metadata:
  name: moduletest-reset
  labels:
    app.kubernetes/version: {{ .Chart.Version }}
spec:
  schedule: "0 23 * * 3"  # This actually runs every other Wednesday at 23:00. Check jobTemplate.spec.template.spec.containers.command
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 50400 # 14 hours leaving time to investigate failed jobs
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: moduletest-reset-container
              image: ghcr.io/danskernesdigitalebibliotek/dpl-platform/moduletest-reset:mr-2.1.0
              command:
                - /bin/bash
                - -c
                - |
                  week=$(date +%W)
                  if (( week % 2 == 0 )); then
                    ./moduletest-reset.mjs --source {{ .Values.syncConfig.source }} --target {{ .Values.syncConfig.target }}
                  else
                    echo "Not release week and thus not running"
                  fi
              resources:
                requests:
                  memory: 256Mi
                  cpu: 250m
                limits:
                  memory: 512Mi
          serviceAccountName: moduletest-reset-service-account
          tolerations:
            - key: noderole.dplplatform
              operator: Equal
              value: prod
              effect: NoSchedule
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: noderole.dplplatform
                      operator: In
                      values:
                       - prod
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: moduletest-reset-service-account
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: moduletest-reset-role
rules:
- apiGroups: [""]
  resources: [ "pods/exec" ]
  verbs: [ "create" ]
- apiGroups: [ "apps", "" ]
  resources: [ "deployments", "pods", "services", "configmaps" ]
  verbs: [ "get", "list" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moduletest-reset-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: moduletest-reset-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: moduletest-reset-role
  apiGroup: rbac.authorization.k8s.io

---

# INFO Roles and binding allowing the moduletest-reset to gain access to the main configMap, database and CLI-pod

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: moduletest-reset-role
  namespace: {{ .Release.Namespace | replace "moduletest" "main" }}
rules:
- apiGroups: [""]
  resources: [ "pods/exec" ]
  verbs: [ "create" ]
- apiGroups: [ "apps", "" ]
  resources: [ "deployments", "pods", "services", "configmaps" ]
  verbs: [ "get", "list" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moduletest-reset-role-binding
  namespace: {{ .Release.Namespace | replace "moduletest" "main" }}
subjects:
- kind: ServiceAccount
  name: moduletest-reset-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: moduletest-reset-role
  apiGroup: rbac.authorization.k8s.io

