---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root-user-secret
  namespace: minio_test
spec:
  encryptedData:
    rootPassword: AgBFL4xm/ZbYLKg0MPJ7ADayMX3Y2jtekrlzSBAHx8lg/s7R1/CDX/+186Yc0CtGnquncXBjQDyixhcMmRyt/VpBnZPeRt/idlHpTXILHM0kfUf9hWXzdk7g/ocUHabfFFCw0GGbvhvOUJaBJgTQK0OYlhzRVlzmcLQ73Na1mWIz6PBOEcYBiCJrPlMyWsCb2fswGy4JhMoWvSyE3N3Nqx0HjK9jQVxg4dIzZ7rsT/XJPEWqE5NjiQkXljC+n0YBk1gHGm43s6faWyu774BzYcsgJCrLXkOA/zaVqlbvq8OcbdnITaMnyuFNhwKhkFBSZrth9tdvS3tNeKQZvpQhsSA/VkML3GrHSJmrVW8GFvk/Va9xWlp8RvPuhj1p7flH3r3wPjMm6xw1DhYMKfUEWuxWPRl8UUu6+p3FVXiTcy9/xVbbZGO0VTqjhwO4zcPAqThHABuG9HIJvzqd2gVlyRQcuv4RbEHJAHjfBdsaz3PgItGQjsaQyVHZu3UwZ/+AhtCvOCzlNrwqysq5cX/czr/whRhpexvII6o+HR61Dye7a/Y664RkkZpT6CaswjSo4kYYU3cQwXnpGKMV3aknnMU6f3NmvJVr8F4DEAtFSK51a+54/nL2aekTDhdN5dNEu245q6bouXU5SS5V+vNvE9aAzWa9HMW4T2GwasI4AkpFMkFkrnY1CHaffDM80pIAC5PTESuppMqtnzEhjvatwo3RHRPZRTnYQgXmcg==
    rootUser: AgADeNNAnTSw1oAQ71tG9QmnivKbhHVngw/Q2sFa7KhphN7FgnxkerawSgeFmDzKFP9tNPETij1kWHTe+PLkADVi9w+aYF7glDhQV1ZGs43CRime18lF8TIUIS9KHrq67j79gMBd2M9Axckdn1FtbKAO5AagPVjb4bg/+fNypmwQNpD+B9k5oeB/MbBxxl6M3TeHv29fhiq97zP5uDO0uijKFRZ7BovOJ+BsiCouCqvey29zj2DMMGsWX/jCMxYtgNPaCmlSaWcwFBQqPCiENHkpr1so6ZitlhBX6yoRYg7YBNbFBK3CwKMPfZ03GQ2wTj2tfaGOkt7gUH/nL3bTnpbWw90M2pz8Amw3bfPheAYpGel+RZnmxfuwZqFtavHsIJX2G9cNf3CiPlphYUth2qeBCCubWFtZFUr/yJEZcLfa77T4Xu461qLEB+E2D7Yjr6WTAbOVydk3tXbbTIjHTovu6k2uHCnDfy9Cm+SEUOcyFx8NYeE0bSh0UFi+OeAmXL4zi+Q8REIOzsVuPOQumR0Uex/ujbcb7oGAFvNcwEym4tUQm7JaMzl1HEo8aOITR+fLIR6yjmz5b5SSwhAl1nxZHRpG+FWkugzGfbl39+RmcgQu2LrdEwAu9ZnATV72BiLhPP9xX7WRUlj9x9gZfgN3aRvEFJjsMx7WsQUK/d5ELhkIj2lVrNLW8P19+slE98dyRQhJlPAE7hBhrWOSqwoPF0dn57ytptwvZg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-root-user-secret
      namespace: minio_test
    type: Opaque
