---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-root-user-secret
  namespace: minio-test
spec:
  encryptedData:
    rootPassword: AgBliUJWYAAwQeDBw9QzHhxJ2vSZzey1YyBR4DylZtZTZgYqgnAYuPA7Q20mWRbUtc9omQPVoGRDBCkmxF1Mg0Kco0oyV9+QGgiTD6tqPGaKpXgjSMJUNt3M4GUYZgEQd+1tQeeljscbritAgfDuM9PI5hauqw9dyo5Dxrmbdzw/okw+MjCn33T/SfhxqDcUHoh3JH2enWNEWAwsim+J0hug3yjNofULGdJ2XpfDz1yotNTwIg/f8SBV8oC3YkxjjSsDBqCSDn7FXYAbbe77oSYirTwe8R3aXYm4Lr2iyX2bxJk3S5qr+4WxIxCd5TXtXUPrErMyFgit3QwwJ0unvCDkk+eho+Km3Xt3XkjsElm8IaDUAjAtQl3jIbAwtQGOYF7P+a44o3/Ma09tVY9dbPVpHMBZPz1AqtVXqnmGQ8NyC5klH0Lh8nm1QiioZBsGAG31770+l84Cl+Wae3fnB0WqofGumISJVS9UR0scYKI5Pp7fOhIOTRsIglOtGYpVENXaMFEIjekeiOTustNxWLB7nWcJtRc3rkxXNPKFslzoUpaYQUk8nKcxDT4zVSJi2UOxUAiw8+ahONtPtvF+cDfytV6fal3AupB6XMpVA6czxTXPqCTqiU0GQHHyXvT+un/TDbZoBFkq1u6xAmXRGVOvisAF31UL1fENTcXL5kBE6lVQPaMnbcYCVXgG19lBQ1ie8gYpEvKcIOt9nmK3qeXSC7I72cXSHeUVhQ==
    rootUser: AgBcH9G2VwrflA5ya7DiC+U3sZiETf2nuICcAD+Ta4CRrM1LWGstduL2uUxoxlpdnDc18dTUSK7GtpcpvrrtCAnx7dwwMH24kd5AKQ57q88NG1xdW41X6wYrEQg3mTXRlPQEi0rb2ObZkgZd0UInHkucJG5H94ot1k83bCqU0o5NHk2JrV2ea9eLvjeXHDsvYruzbx/NFTCYW+24RUG+wa7a9nXbO62oIW4KPfix9DmdlGMU5LlKt1BjJhZrsIkJy6Bq92QfDwhcukw/FHcDGsN6NaWl3zrDrxGFuAkkCRChxh4Ims2jeOMcxXNyXRsiSdSwDRf1Wh/FjO54mRK0ooIX/++XgEFFvhHcDsgMcZX5qLtSEv9FQwk2UbUOJsiVr1+Pr/zWgjsZtVzRFW8V3lOxS5bl2UFtlhE28MmXKGUUCGxfwT8jp/gH/RwMtB0pfv+dl+epGaOkK1gnUuaX1a+5VHYUXkTk8nPStsrWlcu6dDeM0/WR6ZHyIofIS5fwrixWm9ZrnGAChfZIPaFhPaFhaYsTGP8CM7f5kZGXHZxObO/pbo6/IBmMoohtnGr5dtM+1N3pan7wA1hD/BfWhzdldK5Rmpczb6T9qvuZlvVYyNKlC0ChzElMGwS8qDagkeJNN481HcOisfeIl5PFw+tAhhB5sQXy28b0aOopylAU5v6dkBS1AHz1YuBE3fxQeqEILoE7/2aowXRX7D4Nq3rgbndLyllRKZneHw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-root-user-secret
      namespace: minio-test
    type: Opaque
