---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-minio-secret-key
  namespace: minio-test
spec:
  encryptedData:
    secretKey: AgBrzjkcq3P0iuIBqX3H7Q3Ixgz+N3vMAHKN256+DNLWFxt7bZVaQRN/aVc6Kqd7/n/UJlwbooabZBUrzqAAksZ15d6ChcJHMZgydAqJQosH8xYInkCHctqCvv1sfsZ5xk+DE10Tf5mctSQSNnzLpw/liTAAwQAmujTFCw7stGfO2nOXX3REpK3lej9TfjqzKlBgtWJL9g1xtq2xrMkDYVrgTg8E0agqVMNDfw/uyMost8Z67ZS1xXiiRxG9Vjq42ErfyF0i83LnVhC9825+WnfTpb53g5kzONjlsdh1esGUn9fL+2hBapIZj/4+UhaYeti8OrLPrydDQU/kaSGhzGXm8Lab5jF8837rxiuXJcvliNwaBNo0lkHzBaT9mE5ljOMjXa/a8+9AHt+jRPiPnMlQP7DSri7Vdg3TBCHwgQhUPSC9CoED8nZ+6TmWZwQ6KbFvDQ8aOxCEhwiBb+OrQbeGWr2aqp/9k18Maa2ORBuS6I3h/dCPTvFFNIacFrBO/f7aP3aFFUpoN6923AXchVBs+usy1FX4MoqLS2adM6zKdyHwUIu+YhAM/21kolz8+eMrBHozALtgkg3fA3p1Hb+g76DqUw01y4BiI81X2Axcw+b+EuDb5MkXJh4DH8YekclEKrUFe36bGmG5rusvSUS6BEJ9/+4LJXJyIgiFcc2pugD7FpHWLleiiuxBRMOwaeMHK4mMlraD4Rh0OUp1Bzxa11eHJPR1erEVVrtmPqRyS2sR+7nIgZyxTW3olfBODVPb
  template:
    metadata:
      creationTimestamp: null
      name: loki-minio-secret-key
      namespace: minio-test
    type: Opaque
