---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret-key
  namespace: minio_test
spec:
  encryptedData:
    secretKey: AgCM+/9pR1Y/necQz5qWNo4wF4Ngcqeq5bJkxD7ln8agQTNaQ51jCekQgom/XkuhUYwRggvB9x1Nt9bHxUo4rGD0HhMgDiH94YFebn3zaezzXx4QMxynqJPFBxmdzLLW7F/UOe2trhG3WnzuBtHI+q4TxUK1BkDfRA1qyr9c8qIpbi19T2dpLurTYkm5Pj9V3lco3DNmJHScMdB07zIBhux482JbDHGOnX8i4f2gmV4AEVDVrO8YWBAv9rRrpcfoNh6v7F8FBm/IekyS8UaEVwNYgkxAqEuIkW1AgiCcg3XbTJE5q0Wzx5evsywuiT+F294Kaaa/Oj2HFW87od+pPLPeIVkw42AUzTJ2zVC2s0Ki/Ngt+IDRcqA/PjIrrIHzLAaYov5J7ApRX/wLS3nniSE47e0NckwuKLhn4N3N+hMmviGgL+eIrnVrZkCkVzvl062JAyny3QvAG49eS6VptAoB6xfTxLeEPhEy0vA5ZrWTit4HnBq5u9FTm5OlfqnH+W5XT021UNlW+DQHI52oWdjid2nMBV0CQaX3K/wfAis35IoU+LjGiyhKXgr3TsF+6Zanje+VngZZfdjmiWuN1cVIvSuoTOje/OTL1mPgRL9l8bZWaTRGJegx+BOhe0VbzI9IBbfg1IvmBfUTQZ+q6GhmVNEQxVYSOSDsRyluvWvs+YKMMel5Y+jP5WKBfNVO5ZoiZl5D168dY8Nae6eCwF4CjyyzuoWAA9EtcQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret-key
      namespace: minio_test
    type: Opaque
