---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret-key
  namespace: minio-test
spec:
  encryptedData:
    secretKey: AgApSmwuU+88IsU2lPCNgpV0qXd4bqeo6YwvZ6Romzx2a7niiCzG2zl0/jQ6vLBBhEchyIBlsUZteA4j6SpJa1uruIUIdSifw7oWLupietc0mRS9WPSsbdwcOgOgtKIybfr0+nhAbQ7L1XHSYrHoUjcQNjBro+oGVZfkWGxSutv7+FLqClaeKLT+1Semhb9fWkUmZvd6Tuf8jBiEzdaNDZ4xt1/f4/3tbVwmCV5bkNAvyh2y9XhxKNmtSvp3Cv+tL2HkknlgVHMxBwbuTBthgNE4foTHMkDjko+yVi+o4lJYEJWzr1nsJpv9aQZ7c4iUb5XJs6UXWlcsNvL1zymVZawFAH0dyCYYryeggMrfp494qrIaj0JK5ofhx7/eIgOyaB1G1xzm9vjukhieziJrPzhJKQyVC5gUBBaBdp09DnJYZ7X/6Q97ntqnJL27HJ9qKuqT+lnyurMPa6VBwd23+BffoWoTbVM0JZjVHwQiv2Ba+0C4uQ1Nsy2qFWAfvXMoDqaaYQwBDxFpzu3gvfKu+sPHpC8UQqJabj63jf8m4ewhobXjnOcWgJNjX6vQDwN520irgFIlis7JKfng8ys5ei2bXMNnX8gyVCEnyNfMGHT1eMxTH6D+vPRBDf1b3BbGiQC2umKQPtUBCREa6hxT74n1kLuSm9/z673uvHwWKTCi0wv4iBhegW1BPiv+Luq9YExgGwLPFaqlDddZ1JFJgvt4reSLzdwYJHWiKQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret-key
      namespace: minio-test
    type: Opaque
