annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: vestiges of harbor support
    - kind: added
      description: add support for project cloning task image
    - kind: changed
      description: change keycloak rollout strategy to recreate
    - kind: changed
      description: update trivy image to 0.70.0
    - kind: changed
      description: update insights-handler to v0.0.12
    - kind: changed
      description: update legacy ui pinned image to core-v2.32.0
    - kind: changed
      description: changed build-deploy-image to core-v2.32.0
    - kind: changed
      description: fixed beta-ui version to v0.1.0
    - kind: changed
      description: update lagoon appVersion to 2.32.0
apiVersion: v2
appVersion: v2.32.0
dependencies:
- condition: nats.enabled
  name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: ~1.3.0
description: 'A Helm chart for Kubernetes which deploys Lagoon''s core components. '
home: https://github.com/uselagoon/lagoon-charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
kubeVersion: '>= 1.25.0-0'
maintainers:
- email: scott.leggett@amazee.io
  name: smlx
  url: https://amazee.io
- email: ben.jackson@amazee.io
  name: shreddedbacon
  url: https://amazee.io
name: lagoon-core
type: application
version: 1.61.0
